export enum FailureCategory {
  APPLICATION_EXECUTION_ERROR = 'APPLICATION_EXECUTION_ERROR',

  NETWORK_ERROR = 'NETWORK_ERROR',

  RATE_LIMIT = 'RATE_LIMIT',

  INVALID_DATA = 'INVALID_DATA',

  PROVIDER_ERROR = 'PROVIDER_ERROR',

  WEBSITE_UNREACHABLE = 'WEBSITE_UNREACHABLE',

  SCRAPE_ERROR = 'SCRAPE_ERROR',

  QUALIFICATION_ERROR = 'QUALIFICATION_ERROR',

  AI_ANALYSIS_ERROR = 'AI_ANALYSIS_ERROR',

  OUTREACH_ERROR = 'OUTREACH_ERROR',

  FOLLOWUP_ERROR = 'FOLLOWUP_ERROR',

  DATABASE_ERROR = 'DATABASE_ERROR',

  UNKNOWN = 'UNKNOWN',
}
