export enum ScrapingStage {
  SCRAPING = 'SCRAPING',

  SCRAPED = 'SCRAPED',

  PROFILING = 'PROFILING',
  PROFILED = 'PROFILED',
  PROFILE_FAILED = 'PROFILE_FAILED',
}

export enum ScrapeStatus {
  SUCCESS = 'SUCCESS',
  PARTIAL = 'PARTIAL',
  EMPTY = 'EMPTY',

  REDIRECTED = 'REDIRECTED',
  CLOUDFLARE = 'CLOUDFLARE',
  CAPTCHA = 'CAPTCHA',

  ACCESS_DENIED = 'ACCESS_DENIED',
  LOGIN_REQUIRED = 'LOGIN_REQUIRED',

  TIMEOUT = 'TIMEOUT',
  DNS_ERROR = 'DNS_ERROR',

  FAILED = 'FAILED',
}
