export enum DomainEvent {
  LEAD_ACQUISITION = 'LEAD_ACQUISITION',
  LEAD_CREATED = 'LEAD_CREATED',

  SCRAPING_STARTED = 'SCRAPING_STARTED',
  WEBSITE_SCRAPED = 'WEBSITE_SCRAPED',

  LEAD_QUALIFICATION_STARTED = 'LEAD_QUALIFICATION_STARTED',
  LEAD_QUALIFIED = 'LEAD_QUALIFIED',

  LEAD_REJECTED = 'LEAD_REJECTED',

  AI_ANALYSIS = 'AI_ANALYSIS',

  OUTREACH_SENT = 'OUTREACH_SENT',

  REPLY_RECEIVED = 'REPLY_RECEIVED',
}
