import { AIService } from '@/modules/ai/ai.service';
import { OutreachMessage } from '@/modules/ai/model/aiAnalysis.interface';
import { LeadContact } from '@/modules/lead/lead-contact/lead-contact.schema';
import {
  ContactSource,
  ContactStatus,
  ContactType,
} from '@/modules/lead/lead-contact/lead-contact.types';
import { LeadsRepository } from '@/modules/lead/leads.repository';
import { OutreachMessageRepository } from '@/modules/outreach/outreach-message/outreachMessage.repository';
import { OutreachWebhookService } from '@/modules/outreach/outreach-webhook/outreachWebhook.service';
import { IOutreach } from '@/modules/outreach/outreach/model/outreach.interface';
import { OutreachRepository } from '@/modules/outreach/outreach/outreach.repository';
import { ResponseType } from '@/providers/ai/types/AIResponse';
import { S3Service } from '@/providers/communication/email/aws-ses/S3Service';
import { EmailService } from '@/providers/communication/email/EmailService';
import { EmailParser } from '@/providers/communication/email/helpers/emailParser';
import { logger } from '@/shared/logger/logger';

export class EmailDiagnosticsService {
  // Email pipeline Stages:
  // - SES outbound (credentials, rendering, delivery)
  // - S3 retrieval (raw email access)
  // - Mail parsing (Message-ID, In-Reply-To, References, attachments)
  // - Conversation threading
  // - Inbound message persistence
  // - BullMQ enqueueing
  // - AI response generation
  // - Outbound reply via SES

  static leadContact: LeadContact = {
    id: 'TEST-CONTACT',
    name: 'Zain Saeed',
    value: 'zainsaeed067@gmail.com',
    designation: 'Founder',
    type: ContactType.EMAIL,
    status: ContactStatus.ACTIVE,
    source: ContactSource.ADMIN,
    confidence: 90,
    verified: true,
    isPrimary: true,
  };

  static message: OutreachMessage = {
    subject: 'AWS SES Integration Test',
    greeting: 'Hi',
    opening: 'This email was generated by the AI-VBD Email Diagnostics module.',
    message: `
        <p>If you are reading this email, then:</p>

        <ul>
          <li>✅ HTML rendering is working.</li>
          <li>✅ AWS SES credentials are valid.</li>
          <li>✅ MAIL FROM domain is configured.</li>
          <li>✅ Configuration Set is attached.</li>
          <li>✅ Production email template rendered successfully.</li>
        </ul>

        <p>
          Next step is replying to this email to verify the complete
          inbound pipeline (SES → S3 → SNS → Webhook → Queue).
        </p>
      `,
    closing:
      'This is an automated diagnostics email. No action is required except replying if you wish to test inbound processing.',
  };

  static businessName: 'Nestra Technologies';

  static async sendTestEmail() {
    const html = await EmailService.renderEmailHtml({
      contact: this.leadContact,
      businessName: this.businessName,
      message: this.message,
    });

    const subject = `AWS SES Integration Test - ${new Date().toISOString()}`;

    const result = await EmailService.send({
      to: this.leadContact.value,
      subject,
      html,
    });

    logger.info(
      {
        provider: result.provider,
        providerMessageId: result.providerMessageId,
      },
      'AWS SES Diagnostics Email Sent',
    );

    return {
      success: result.success,
      provider: result.provider,
      providerMessageId: result.providerMessageId,
      sentAt: new Date(),
    };
  }

  static async sendTestOutreach() {
    const html = await EmailService.renderEmailHtml({
      contact: this.leadContact,
      businessName: this.businessName,
      message: this.message,
    });

    const subject = `AWS SES Integration Test - ${new Date().toISOString()}`;

    const result = await EmailService.send({
      to: 'zainsaeed067@gmail.com',
      subject,
      html,
    });

    logger.info(
      {
        provider: result.provider,
        providerMessageId: result.providerMessageId,
      },
      'AWS SES Diagnostics Email Sent',
    );

    return {
      success: result.success,
      provider: result.provider,
      providerMessageId: result.providerMessageId,
      sentAt: new Date(),
    };
  }

  static async sendTestFollowup(outreachId: string, recipient: string) {
    // Load outreach
    // ↓
    // AI.generateResponse()
    // ↓
    // renderEmailHtml()
    // ↓
    // EmailService.send()
    // ↓
    // return providerMessageId

    const outreach = await OutreachRepository.findById(outreachId);

    if (!outreach) throw new Error('Outreach not found');

    const lead = await LeadsRepository.findById(outreach.leadId);

    if (!lead) throw new Error('Lead not found');

    const contact = {
      ...this.leadContact,
      value: recipient ?? this.leadContact.value,
    };

    return this.sendGeneratedEmail({
      outreach,
      contact,
      businessName: lead.businessName,
      responseType: ResponseType.FOLLOW_UP,
    });
  }

  static async sendTestResponse(outreachMessageId: string, recipient?: string) {
    const inbound = await OutreachMessageRepository.findById(outreachMessageId);

    if (!inbound) {
      throw new Error('Inbound message not found');
    }

    const outreach = await OutreachRepository.findById(inbound.outreachId);

    if (!outreach) {
      throw new Error('Outreach not found');
    }

    const lead = await LeadsRepository.findById(outreach.leadId);

    if (!lead) {
      throw new Error('Lead not found');
    }

    const contact = {
      ...this.leadContact,
      value: recipient ?? this.leadContact.value,
    };

    return this.sendGeneratedEmail({
      outreach,
      contact,
      businessName: lead.businessName,
      responseType: ResponseType.REPLY,
    });
  }

  private static async sendGeneratedEmail({
    outreach,
    contact,
    businessName,
    responseType,
  }: {
    outreach: IOutreach;
    contact: LeadContact;
    businessName: string;
    responseType: ResponseType;
  }) {
    const ai = new AIService();
    const generated = await ai.generateResponse(outreach, responseType);

    const html = await EmailService.renderEmailHtml({
      contact,
      businessName,
      message: generated,
    });

    const result = await EmailService.send({
      to: contact.value,
      subject: generated.subject,
      html,
    });

    return {
      success: result.success,
      provider: result.provider,
      providerMessageId: result.providerMessageId,

      generated,
      html,
    };
  }

  // Parsing and Data Fetching
  static async testS3Download(objectKey: string) {
    const raw = await S3Service.getEmail(objectKey);

    return {
      success: true,
      objectKey,
      size: raw.length,
      preview: raw.substring(0, 500),
    };
  }

  static async testMailParser(objectKey: string) {
    const raw = await S3Service.getEmail(objectKey);

    const parsed = await EmailParser.parse(raw);

    return parsed;

    // Helps to inspect:
    // - messageId
    // - inReplyTo
    // - references
    // - html
    // - text
    // - attachments
  }

  static async testThreadResolution(objectKey: string) {
    const parsed = await this.testMailParser(objectKey);

    let parent = parsed.inReplyTo
      ? await OutreachMessageRepository.findByExternalMessageId(
          parsed.inReplyTo,
        )
      : null;

    if (!parent && parsed.references.length > 0) {
      parent = await OutreachMessageRepository.findLatestByExternalMessageIds(
        parsed.references,
      );
    }

    return {
      found: !!parent,
      parentMessage: parent,
      parsed,
    };
  }

  // Simulate Webhooks
  static async testHandleIncomingEmail(objectKey: string) {
    const notification = {
      mail: {
        messageId: `TEST-${Date.now()}`,
      },

      receipt: {
        action: {
          objectKey,
        },
      },
    };

    await OutreachWebhookService.handleIncomingEmail(notification);

    return {
      success: true,
      objectKey,
    };
  }

  static async testReplaySnsPayload(payload: any) {
    await OutreachWebhookService.handleSesNotification(payload);

    return {
      success: true,
    };
  }

  static async testCompleteInboundPipeline(objectKey: string) {
    const parsed = await this.testMailParser(objectKey);

    const thread = await this.testThreadResolution(objectKey);

    await this.testHandleIncomingEmail(objectKey);

    return {
      success: true,
      parsed,
      thread,
    };
  }
}
